import type { Folder } from '../types/Folder'

export const folders: Folder[] = [
  {
    id: 1n,
    parent_id: null,
    member_id: 1n,
    name: '프로젝트',
    order: 1,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 2n,
    parent_id: 1n,
    member_id: 1n,
    name: '프론트엔드',
    order: 1,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 3n,
    parent_id: 1n,
    member_id: 1n,
    name: '백엔드',
    order: 2,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 4n,
    parent_id: 2n,
    member_id: 1n,
    name: '컴포넌트',
    order: 1,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 5n,
    parent_id: 2n,
    member_id: 1n,
    name: '페이지',
    order: 2,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 6n,
    parent_id: null,
    member_id: 1n,
    name: '개인',
    order: 2,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 7n,
    parent_id: 6n,
    member_id: 1n,
    name: '가계부',
    order: 1,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
]
