import type { Folder } from '../types/Folder'

export const folders: Folder[] = [
  {
    id: 1n,
    parent_id: null,
    member_id: 1n,
    name: '1차 프로젝트',
    order: 1,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 2n,
    parent_id: 1n,
    member_id: 1n,
    name: '기획',
    order: 1,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 3n,
    parent_id: 1n,
    member_id: 1n,
    name: '사용자 인터뷰',
    order: 2,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 4n,
    parent_id: 1n,
    member_id: 1n,
    name: 'UI 디자인',
    order: 1,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 5n,
    parent_id: 1n,
    member_id: 1n,
    name: '사용자 인터뷰',
    order: 2,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 9n,
    parent_id: 1n,
    member_id: 1n,
    name: '기타',
    order: 2,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 6n,
    parent_id: null,
    member_id: 1n,
    name: '2차 프로젝트',
    order: 2,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
  {
    id: 7n,
    parent_id: 6n,
    member_id: 1n,
    name: '기획',
    order: 1,
    created_at: '',
    modified_at: '',
    deleted_at: null,
    is_deleted: false,
  },
]
